project_id = "jgdyklzrxygvwuhlnbat"

[functions.whatsapp-evolution]
verify_jwt = false

[functions.create-tenant]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = true

[functions.qz-sign]
verify_jwt = false

[functions.orders-create]
verify_jwt = false

[functions.orders-webhook]
verify_jwt = false

[functions.orders-status]
verify_jwt = true